FROM php:8.1.10-fpm-alpine3.16

RUN apk add --no-cache openssl bash vim mysql-client

RUN docker-php-ext-install pdo pdo_mysql bcmath
# RUN docker-php-source extract \
# 	pdo pdo_mysql mbstring exif pcntl bcmath gd \
# 	&& docker-php-source delete

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY . /var/www/

RUN adduser -D www 

USER www
WORKDIR /var/www/

EXPOSE 9000
ENTRYPOINT ["php-fpm"]